import { ROLES } from "@/constants/roles";

export const PERMISSIONS = {
  VIEW_DASHBOARD: "view:dashboard",

  VIEW_AREAS: "view:areas",
  MANAGE_AREAS: "manage:areas",

  VIEW_BINS: "view:bins",
  MANAGE_BINS: "manage:bins",

  VIEW_TELEMETRY: "view:telemetry",
  VIEW_ALERTS: "view:alerts",
  VIEW_ANALYTICS: "view:analytics",

  VIEW_SETTINGS: "view:settings",
  VIEW_PROFILE: "view:profile",
  VIEW_NOTIFICATIONS: "view:notifications",
  VIEW_SECURITY: "view:security",
  VIEW_APPEARANCE: "view:appearance",

  VIEW_USERS: "view:users",
  MANAGE_USERS: "manage:users",

  VIEW_ROLES: "view:roles",
  MANAGE_ROLES: "manage:roles",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_AREAS,

    PERMISSIONS.VIEW_BINS,
    PERMISSIONS.MANAGE_BINS,

    PERMISSIONS.VIEW_TELEMETRY,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_ANALYTICS,

    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_SECURITY,
    PERMISSIONS.VIEW_APPEARANCE,

    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_ROLES,
  ],

  [ROLES.WORKER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_BINS,
    PERMISSIONS.VIEW_TELEMETRY,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
};
